### ISSUE TITLE
Plans for other python versions

### ISSUE THREAD

**Issue by robvanderg** [Masonshipton25/URIELPlus#2]
Thanks for this nice toolkit!  

Are there any plans to widen the python requirements?, something like 3.7-3.13 would make the tool much easier usable. 

What are the reasons that it is so narrow?, I have 3.12, and I couldn't install tensorflow-addons, are there other issues as well?

**Comment by Masonshipton25** [comment]
Thank you for the compliment! As you mentioned, the specific Python version requirements were due to tensorflow-addons, which is only needed for MIDASpy imputation. We’ve now modified the setup so that the normal installation supports any Python version 3.10 or later. Installing MIDASpy is optional and requires a Python version earlier than 3.11.
